// swift-tools-version:5.9
//
// Phase 0 SwiftPM sample — consumes the local `SignerCore.xcframework`
// produced by `../build-ios.sh` and exercises `ping()` through a unit test.
// This is a throwaway fixture, not the real iOS app (which lives in
// clad-mobile/iosApp and only consumes signer-core starting in Phase 3).
//
// Layout:
//   ios/
//     Package.swift                        <-- you are here
//     Sources/SignerCore/SignerCore.swift  <-- generated by build-ios.sh
//     Tests/SignerCoreTests/PingTests.swift
//   build/ios/SignerCore.xcframework       <-- produced by build-ios.sh
import PackageDescription

let package = Package(
    name: "SignerCoreSample",
    platforms: [
        // aarch64-apple-ios-sim requires iOS 13+; macOS slice isn't built in
        // Phase 0, so tests run through `xcodebuild -destination 'platform=iOS Simulator'`.
        .iOS(.v13)
    ],
    products: [
        .library(name: "SignerCore", targets: ["SignerCore"])
    ],
    targets: [
        // The UniFFI-generated Swift wrapper. Depends on SignerCoreFFI (the
        // binary slice containing the Rust staticlib + C header + modulemap).
        .target(
            name: "SignerCore",
            dependencies: ["SignerCoreFFI"],
            path: "Sources/SignerCore"
        ),
        // Binary target pointing at the locally-built xcframework. Regenerate
        // via `../build-ios.sh` before `swift test` or `xcodebuild test`.
        .binaryTarget(
            name: "SignerCoreFFI",
            path: "../build/ios/SignerCore.xcframework"
        ),
        .testTarget(
            name: "SignerCoreTests",
            dependencies: ["SignerCore"],
            path: "Tests/SignerCoreTests"
        )
    ]
)
