//! Autogenerated weights for pallet_clad_token
//!
//! THIS FILE WAS AUTO-GENERATED USING ESTIMATED WEIGHTS BASED ON BENCHMARK STRUCTURE
//! IT IS NOT RECOMMENDED FOR PRODUCTION USE
//! Run benchmarks with a live node to get accurate production weights
//!
//! Command to generate production weights:
//! ```bash
//! frame-omni-bencher v1 benchmark pallet \
//!   --runtime target/release/wbuild/clad-runtime/clad_runtime.compact.compressed.wasm \
//!   --pallet "pallet_clad_token" \
//!   --extrinsic "" \
//!   --template ./pallets/benchmarking/frame-umbrella-weight-template.hbs \
//!   --output ./pallets/clad-token/src/weights.rs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_clad_token.
pub trait WeightInfo {
	fn mint() -> Weight;
	fn transfer() -> Weight;
	fn freeze() -> Weight;
	fn unfreeze() -> Weight;
	fn add_to_whitelist() -> Weight;
	fn remove_from_whitelist() -> Weight;
}

/// Estimated weights for pallet_clad_token (generated from benchmarking structure).
/// These weights are NOT production-ready and should be replaced with actual benchmarked values.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: CladToken TotalSupply (r:1 w:1)
	/// Proof: CladToken TotalSupply (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: CladToken Balances (r:1 w:1)
	/// Proof: CladToken Balances (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn mint() -> Weight {
		// Estimated complexity: 2 reads, 2 writes
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: CladToken Whitelist (r:2 w:0)
	/// Proof: CladToken Whitelist (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: CladToken Frozen (r:1 w:0)
	/// Proof: CladToken Frozen (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: CladToken Balances (r:2 w:2)
	/// Proof: CladToken Balances (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn transfer() -> Weight {
		// Estimated complexity: 5 reads, 2 writes
		Weight::from_parts(75_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: CladToken Frozen (r:0 w:1)
	/// Proof: CladToken Frozen (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	fn freeze() -> Weight {
		// Estimated complexity: 0 reads, 1 write
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: CladToken Frozen (r:0 w:1)
	/// Proof: CladToken Frozen (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	fn unfreeze() -> Weight {
		// Estimated complexity: 0 reads, 1 write
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: CladToken Whitelist (r:0 w:1)
	/// Proof: CladToken Whitelist (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	fn add_to_whitelist() -> Weight {
		// Estimated complexity: 0 reads, 1 write
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: CladToken Whitelist (r:0 w:1)
	/// Proof: CladToken Whitelist (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	fn remove_from_whitelist() -> Weight {
		// Estimated complexity: 0 reads, 1 write
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn mint() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn transfer() -> Weight {
		Weight::from_parts(75_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn freeze() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn unfreeze() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn add_to_whitelist() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn remove_from_whitelist() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
