//! Kotlin-oracle corpus tests for SR25519 verify and Blake2b-256.
//!
//! Vectors are generated by `UosCryptoCorpusExport` (Kotlin JVM test) using
//! `sr25519-kotlin` and BouncyCastle as oracles. Rust verifies — it never
//! re-signs. Run the exporter to regenerate:
//!
//!   cd clad-mobile
//!   ./gradlew :shared:jvmTest --tests "tech.wideas.clad.crypto.UosCryptoCorpusExport"

use signer_core::{blake2, sr25519};
use std::path::Path;

fn corpora_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpora/crypto")
}

#[test]
fn sr25519_verify_kotlin_oracle() {
    let path = corpora_dir().join("sr25519_verify.json");
    let raw = std::fs::read_to_string(&path).expect("sr25519_verify.json missing");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("parse sr25519_verify.json");

    for vector in v["vectors"].as_array().expect("vectors array missing") {
        let desc = vector["description"].as_str().unwrap_or("?");
        let msg_hex = vector["input"]["message_hex"].as_str().unwrap();
        let pk_hex = vector["input"]["public_key_hex"].as_str().unwrap();
        let sig_hex = vector["expected_signature_hex"].as_str().unwrap();

        let message = if msg_hex.is_empty() { vec![] } else { hex::decode(msg_hex).unwrap() };
        let public_key = hex::decode(pk_hex).unwrap();
        let signature = hex::decode(sig_hex).unwrap();

        assert_eq!(public_key.len(), 32, "public key must be 32 bytes: {desc}");
        assert_eq!(signature.len(), 64, "signature must be 64 bytes: {desc}");

        assert!(
            sr25519::verify(&message, &signature, &public_key),
            "sr25519::verify failed for vector: {desc}",
        );
    }
}

#[test]
fn blake2b_256_kotlin_oracle() {
    let path = corpora_dir().join("blake2b_256_oracle.json");
    let raw = std::fs::read_to_string(&path).expect("blake2b_256_oracle.json missing");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("parse blake2b_256_oracle.json");

    for vector in v["vectors"].as_array().expect("vectors array missing") {
        let desc = vector["description"].as_str().unwrap_or("?");
        let input_hex = vector["input_hex"].as_str().unwrap();
        let expected_hex = vector["expected_hash_hex"].as_str().unwrap();

        let input = if input_hex.is_empty() { vec![] } else { hex::decode(input_hex).unwrap() };
        let got = blake2::blake2b_256(&input);
        assert_eq!(hex::encode(&got), expected_hex, "blake2b_256 mismatch for vector: {desc}",);
    }
}
